/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#ba9eff',
        'primary-dim': '#8455ef',
        'primary-fixed': '#ae8dff',
        'primary-fixed-dim': '#a27cff',
        'primary-container': '#ae8dff',
        'on-primary': '#39008c',
        'on-primary-fixed': '#000000',
        'on-primary-fixed-variant': '#370086',
        'on-primary-container': '#2b006e',
        secondary: '#00cffc',
        'secondary-dim': '#00c0ea',
        'secondary-fixed': '#80deff',
        'secondary-fixed-dim': '#37d4ff',
        'secondary-container': '#00677f',
        'on-secondary': '#004050',
        'on-secondary-container': '#eef9ff',
        'on-secondary-fixed': '#003a48',
        'on-secondary-fixed-variant': '#00586d',
        tertiary: '#ff97b5',
        'tertiary-dim': '#f0779d',
        'tertiary-fixed': '#ff8eb0',
        'tertiary-fixed-dim': '#f67ca3',
        'tertiary-container': '#fd81a8',
        'on-tertiary': '#6a0934',
        'on-tertiary-container': '#59002a',
        'on-tertiary-fixed': '#380018',
        'on-tertiary-fixed-variant': '#701039',
        error: '#ff6e84',
        'error-dim': '#d73357',
        'error-container': '#a70138',
        'on-error': '#490013',
        'on-error-container': '#ffb2b9',
        background: '#0e0e0e',
        'on-background': '#ffffff',
        surface: '#0e0e0e',
        'surface-dim': '#0e0e0e',
        'surface-bright': '#2c2c2c',
        'surface-container-lowest': '#000000',
        'surface-container-low': '#131313',
        'surface-container': '#1a1a1a',
        'surface-container-high': '#20201f',
        'surface-container-highest': '#262626',
        'surface-variant': '#262626',
        'surface-tint': '#ba9eff',
        'on-surface': '#ffffff',
        'on-surface-variant': '#adaaaa',
        outline: '#767575',
        'outline-variant': '#484847',
        'inverse-primary': '#6e3bd7',
        'inverse-surface': '#fcf9f8',
        'inverse-on-surface': '#565555',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
